### ISSUE TITLE
where the sources you've deleted?

### ISSUE THREAD

**Issue by Gargo** [m-kirsanov/pokemap_live_ios#2]

**Comment by m-kirsanov** [comment]
now only ipa available

**Comment by frdmn** [comment]
Why do you use GitHub then?

**Comment by pixelwix** [comment]
can you please make so we can install with cydia impactor? not all of us are jailboken

**Comment by m-kirsanov** [comment]
@pixelwix ok, i'll rebuild app and update readme after that

**Comment by m-kirsanov** [comment]
new ipa added and install instructions
