### ISSUE TITLE
no pokemon

### ISSUE THREAD

**Issue by pixelwix** [m-kirsanov/pokemap_live_ios#3]
I can't seem to get it to find any Pokemon. I've had version 1.2 installed and running for 5mins and not a single Pokemon has popped up on the map. :(

**Comment by m-kirsanov** [comment]
@pixelwix hm, maybe there are no pokemons around your location? with last niantic api changes max radius for one scan is about 200meters, and one scan takes about 1 min. Plus app can receive pokemon data from my server(each user shares pokemons with others through it), but currently app has a little users count.

**Comment by pixelwix** [comment]
no I'm pretty sure theres pokemone within the 200m radius.. this is ipoke go client using th Pokemongo-map server [https://cl.ly/h2iJ](url) and yours [https://cl.ly/h2m0](url)

**Comment by m-kirsanov** [comment]
@pixelwix is spinner on bottom always visible?

**Comment by pixelwix** [comment]
yes

**Comment by m-kirsanov** [comment]
@pixelwix ok, i'll try to find problem, you have some bug with auth. Please close app and try open later.

**Comment by pixelwix** [comment]
is it possible for us to sign in using the ptc account like the old one?

**Comment by m-kirsanov** [comment]
@pixelwix i will add this feature in next release (PTC/google)

**Comment by pixelwix** [comment]
ok thanks

**Comment by chriscakes** [comment]
I have the same problem.. no pokemons are showing and the spinner is showing all the time.. had it up for about 5 minutes aswell

**Comment by m-kirsanov** [comment]
1.3 release
