### ISSUE TITLE
no pokemons aswell

### ISSUE THREAD

**Issue by chriscakes** [m-kirsanov/pokemap_live_ios#4]
no pokemons are showing for me either.. the spinner is loading and everything but no pokemons are showing

**Comment by chriscakes** [comment]
seems like the scan is never ending or something..

**Comment by chriscakes** [comment]
the app maybe not working in sweden?

**Comment by m-kirsanov** [comment]
@chriscakes they added captcha to pokemon club registration, will release update with manual login today

**Comment by chriscakes** [comment]
i only have google account

**Comment by m-kirsanov** [comment]
@chriscakes 1.3 release
